### ISSUE TITLE
Standardize project page slides

### ISSUE THREAD

**Issue by alex-bellon** [rolsanmordua/waitlisters-website#1]
The container is currently the size of largest slide. We should fix it to change, or use a different structure (I suggest a list)

**Comment by rolsanmordua** [comment]
Correct, the container is hard-coded to be the size of the largest slide. We need to look into A) making it dynamically adjust to the content or B) a better layout. I veto a list because that's what we had before. We have several projects as it is and I don't think a super long page to scroll produces the best UX. I'd consider a grid where you can tap/click on a project expanding to show details.

**Comment by rolsanmordua** [comment]
Goals
- Implement a user-friendly interface to browse org projects that is both functional and versatile
